python3 train_clean.py \
    --feature_type 'uni' \
    --train_df '/raid/CPTAC/splits/train_df.csv' \
    --val_df '/raid/CPTAC/splits/val_df.csv' \
    --test_df '/raid/CPTAC/splits/test_df.csv' \
    --feat_path '/raid/CPTAC/protoattn_feats/all_feats' \
    --save_root '/raid/CPTAC/protoattn_feats' \
    --exp_name 'protoattn_1e-6' \
    --task 'cptac_lung' \
    --task_type 'binary' \
    --lr 1e-6